language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - nosetests
  - coverage py_stringmatching/tests/test_simfunctions.py
  - coverage py_stringmatching/tests/test_tokenizers.py

after_success:
  - codecov
