
environment:

  matrix:
    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"

    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"

    - PYTHON: "C:\\Python34_32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      CONDA_PY: "34"

    - PYTHON: "C:\\Python34_64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      CONDA_PY: "34"


install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit)
  - powershell .\\continuous-integration\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Don't install from requirements-pip.txt, python-coveralls has broken dependencies on windows it seems.
  - conda install --yes setuptools nose numpy pip coverage 
  - pip install six python-Levenshtein rednose
  - python setup.py install

build: false

test_script:
  # Nosetests take care of unit tests
  # Behave runs the example scripts and tries to verify if it produces the right output
  - nosetests
  #- behave --tags ~@skip # Everything without the tag @skip

on_success:
  # Could run coveralls here but will leave that to travis tests
  - echo Build succesful!
  #- coverage report
  # coveralls
